version: "3.7"
services: 
    rabbitmq:
      image: rabbitmq
      hostname: rabbitmq
      command: rabbitmq-server
      ports: 
        - "15672:15672"
        - "5672:5672"
      volumes:
        - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    nodeapp:
      image: "hellochokchok/backend:latest"
      ports:
        - "8081:8081"
      restart: on-failure
      links: 
        - rabbitmq
        - nginx
      depends_on:
        - rabbitmq
        - nginx
    nginx:
      image: nginx
      hostname: nginx
      ports:
        - "80:80"

    