version: "3.7"
services: 
    rabbitmq:
      image: rabbitmq
      hostname: rabbitmq
      command: rabbitmq-server
      ports: 
        - "15672:15672"
        - "5672:5672"
      volumes:
        - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    nodeapp:
      hostname: nodeapp
      image: "hellochokchok/backend:latest"
      ports:
        - "8081"
      restart: on-failure
      links: 
        - rabbitmq
      depends_on:
        - rabbitmq
    nginx:
      image: nginx
      hostname: nginx
      volumes: 
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "80:80"
      restart: always
      links:
        - nodeapp
      depends_on:
        - nodeapp


    