version: "3.7"
services: 
    rabbitmq:
      image: rabbitmq
      hostname: rabbitmq
      command: rabbitmq-server
      ports: 
        - "15672:15672"
        - "5672:5672"
      volumes:
        - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      restarts: always
    nodeapp:
      image: "hellochokchok/backend:latest"
      ports:
        - "8081:8081"
      restart: always
      links: 
        - rabbitmq
      depends_on:
        - rabbitmq
    